apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ffp6ma4om-nodejs
  janus-idp.io/tekton: ffp6ma4om-nodejs
  backstage.io/kubernetes-id: ffp6ma4om-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ffp6ma4om-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
