apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ffp6ma4om-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ffp6ma4om-nodejs 
  name: ffp6ma4om-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ffp6ma4om-nodejs 
